### ISSUE TITLE
Command 'glassit.increase' not found

### ISSUE THREAD

**Issue by angelzarza** [hikarin522/GlassIt-VSC#45]
As of this [version](https://code.visualstudio.com/updates/v1_75) the extension stopped working causing the error: (command 'glassit.increase' not found) when trying to use the shortcut ctrl+alt+z.

**Comment by aygharib** [comment]
This extension was working for me in VSCode on Ubuntu 22.10, but seems to have stopped working as of a few weeks ago. I believe it happened after I upgraded as @angelzarza said.

**Comment by PotatoesFall** [comment]
@aygharib @angelzarza perhaps you should check the extension logs to see what is going wrong. Ctrl+Shift+P (command palette) > Developer: Show Logs > Extension Host

**Comment by angelzarza** [comment]
@PotatoesFall 

[info] ExtensionService#_doActivateExtension s-nlf-fh.glassit, startup: true, activationEvent: '*'
[error] Activating extension s-nlf-fh.glassit failed due to an error:
[error] Error: Command failed: pgrep 119
	at checkExecSyncError (node:child_process:848:11)
	at Object.execSync (node:child_process:922:15)
	at Object.execSync (node:electron/js2c/asar_bundle:5:12704)
	at activate (/home/angel/.vscode/extensions/s-nlf-fh.glassit-0.2.5/extension.js:55:35)
	at Ui.db (/snap/code/119/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14818)
	at Ui.cb (/snap/code/119/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14519)
	at /snap/code/119/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12519
	at async f.n (/snap/code/119/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/snap/code/119/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/snap/code/119/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)`

**Comment by aygharib** [comment]
Problem looks to be resolved after #46 was merged. Thanks for the help @PotatoesFall

**Comment by aygharib** [comment]
@angelzarza Can you close this issue if the problem has been fixed on your end as well?
